version: '3'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data:cached
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app: &app
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - RUBY_VERSION=${APP_RUBY_VERSION}
        - PG_MAJOR=${APP_PG_MAJOR}
        - NODE_MAJOR=${APP_NODE_MAJOR}
        - YARN_VERSION=${APP_YARN_VERSION}
        - BUNDLER_VERSION=${APP_BUNDLER_VERSION}
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: sh -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app:cached
      - app-bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        - NODE_VERSION=${WEB_NODE_VERSION}
    command: sh -c "yarn install --check-files && yarn start"
    volumes:
      - ./web:/web:cached
      - web-node-module:/web/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - app

  solargraph:
    build:
      context: .
      dockerfile: ./docker/solargraph/Dockerfile
      args:
        - RUBY_VERSION=${APP_RUBY_VERSION}
        - BUNDLER_VERSION=${APP_BUNDLER_VERSION}
    command: sh -c "bundle install && bundle exec solargraph socket --host=0.0.0.0 --port=7658"
    volumes:
      - ./solargraph:/solargraph:cached
      - solargraph-bundle:/usr/local/bundle
    ports:
      - "8091:7658"
    links: [] 

volumes:
  dbdata:
  app-bundle:
  web-node-module:
  solargraph-bundle: