version: '3'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data:cached
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - RUBY_VERSION=${APP_RUBY_VERSION}
        - PG_MAJOR=${APP_PG_MAJOR}
        - NODE_MAJOR=${APP_NODE_MAJOR}
        - YARN_VERSION=${APP_YARN_VERSION}
        - BUNDLER_VERSION=${APP_BUNDLER_VERSION}
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        - NODE_VERSION=${WEB_NODE_VERSION}
    command: sh -c "yarn start"
    volumes:
      - ./web:/web:cached
    ports:
      - "3001:3000"
    depends_on:
      - app

volumes:
  dbdata: